# Generated by Django 4.2.10 on 2024-08-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=' ', max_length=100, verbose_name='Название группы'),
            preserve_default=False,
        ),
    ]
